services:
  - type: web
    name: telegram-video-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: PORT
        value: 10000